on: 
 push:
    paths:
    - 'service-1/**'
jobs:
  Deploy-sls-service1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a service-1 deploy."

on: 
 push:
    paths:
    - 'service-2/**'
jobs:
  Deploy-sls-service2:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a service-2 deploy."