on: 
 push:
    paths:
    - 'hello/**'
jobs:
  Deploy-sls-hello:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v1
     - uses: actions/setup-node@v1
       with:
         node-version: '12.x'
     - name: Install Serverless Framework
       run: npm install -g serverless
     - name: Deploy hello
       env:
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET }}
         AWS_SESSION_TOKEN: ${{ secrets.AWS_TOKEN }}
       run: |
        cd hello
        sls deploy -s dev