on: 
 push:
    paths:
    - 'hola/**'
jobs:
  Deploy-sls-hola:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v1
     - uses: actions/setup-node@v1
       with:
         node-version: '12.x'
     - name: Install Serverless Framework
       run: npm install -g serverless
     - name: Deploy Hola
       env:
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET }}
       run: |
        echo "deploying hola serverless service"
        cd hola
        sls deploy -s dev
        

